### ISSUE TITLE
button.html template, what it looks like

### ISSUE THREAD

**Issue by ericxin1982** [mkeida/vuette#1]
![image](https://github.com/mkeida/vuette/assets/9047436/41b3d08a-6118-4389-a95f-2ad1c33212b3)

Hi @mkeida 

I saw your response for alpinejs custom element, and I have an issue, but I am not sure how to describe, would you please share me that html file content, I may see something helpful to me, appreciate it!

Thanks
Eric Xin

**Comment by mkeida** [comment]
@ericxin1982 Hello friend! Since I wrote this long time ago, I'm sending you whole project. I hope you will find something helpful 🙌

[th-ui.zip](https://github.com/mkeida/vuette/files/15052003/th-ui.zip)

**Comment by ericxin1982** [comment]
Hi @mkeida 

Thanks so much!

Eric Xin
